spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sysasistencia
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  secret: my-super-secret-key
